wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1678214182.044045
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.13.10
      8:
      - 3
      - 5
git_hash:
  desc: null
  value: 39cb38573450bf21ffe45398110b58dee5a97285
growth_rate:
  desc: null
  value: 1
world_settings:
  desc: null
  value:
    b_agent_amount: 100
    clock_speed: 0
    creature_starting_food: 0.4
    grass_growth_rate: 1
    grid_height: 20
    grid_width: 40
    j_agent_amount: 100
    killing_cost: 0.2
    reproduction_cost: 0.5
    scale: 32
    t_agent_amount: 100
    turning_food_cost: 0.0005
    use_temp: true
    walking_food_cost: 0.002
    walking_in_water_cost: 0.008
