wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_last_episode_starts:
  desc: null
  value: "[ True  True  True  True  True  True  True  True  True  True  True  True\n\
    \  True  True  True  True  True  True  True  True]"
_last_obs:
  desc: null
  value: "[[[[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n \
    \ [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0.\
    \ 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]]\n\n\n [[[0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n \
    \ [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0.\
    \ 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]]]\n\n\n [[[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]]\n\n\n ...\n\
    \n\n [[[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]]\n\n\n [[[0. 0. 0. ... 0. 0. 0.]\n  \
    \ [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n\
    \   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0.\
    \ ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n \
    \  [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0.\
    \ 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n \
    \  ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]]]\n\n\n [[[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n  \
    \ [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0.\
    \ 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n \
    \  ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ...\
    \ 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0.\
    \ 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0.\
    \ 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]\n\n  [[0. 0. 0. ... 0. 0. 0.]\n   [0. 0.\
    \ 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   ...\n   [0. 0. 0. ... 0. 0.\
    \ 0.]\n   [0. 0. 0. ... 0. 0. 0.]\n   [0. 0. 0. ... 0. 0. 0.]]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x00000230B208B400>
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 420000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.10
    start_time: 1678815460.203973
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 22
      - 23
      - 34
      4: 3.10.10
      5: 0.13.10
      8:
      - 3
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(8)
algo:
  desc: null
  value: PPO
batch_size:
  desc: null
  value: 40960
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x00000230AF68AB90>
clip_range_vf:
  desc: null
  value: None
device:
  desc: null
  value: cpu
ent_coef:
  desc: null
  value: 0.0
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_monitor.VecMonitor object at 0x000002308D44BEE0>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
git_hash:
  desc: null
  value: c7443d1b5ec0be83bba199e135e5f1f01757a3b0
growth_rate:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.013333333333333334
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x00000230AF68AA70>
max_grad_norm:
  desc: null
  value: 0.5
n_envs:
  desc: null
  value: 20
n_epochs:
  desc: null
  value: 30
n_steps:
  desc: null
  value: 2048
normalize_advantage:
  desc: null
  value: 'True'
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: "Box([[[0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0.\
    \ 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0.\
    \ 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]]\n\n [[0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0.\
    \ 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0.\
    \ 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]]\n\n [[0. 0. 0.\
    \ 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0.\
    \ 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0.\
    \ 0. 0. 0. 0.]]\n\n [[0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0.\
    \ 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0.\
    \ 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]]\n\n [[0. 0. 0. 0. 0. 0. 0.]\n  [0.\
    \ 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0.\
    \ 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]\n  [0. 0. 0. 0. 0. 0. 0.]]], [[[1.\
    \ 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1.\
    \ 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1.\
    \ 1. 1. 1. 1. 1. 1.]]\n\n [[1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]]\n\n [[1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]]\n\
    \n [[1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]]\n\n [[1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]\n\
    \  [1. 1. 1. 1. 1. 1. 1.]\n  [1. 1. 1. 1. 1. 1. 1.]]], (5, 7, 7), float32)"
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (shared_net): Sequential()\n    (policy_net): Sequential(\n\
    \      (0): Linear(in_features=245, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n    (value_net): Sequential(\n      (0): Linear(in_features=245, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64,\
    \ out_features=8, bias=True)\n  (value_net): Linear(in_features=64, out_features=1,\
    \ bias=True)\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x00000230AF673460>
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1678815461769071300
target_kl:
  desc: null
  value: None
tensorboard_log:
  desc: null
  value: ./tmp/tensorlog/
use_sde:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
vf_coef:
  desc: null
  value: 0.5
world_settings:
  desc: null
  value:
    b_agent_amount: 100
    clock_speed: 0
    creature_starting_food: 0.4
    grass_growth_rate: 1
    grid_height: 20
    grid_width: 40
    j_agent_amount: 100
    killing_cost: 0.2
    reproduction_cost: 0.5
    scale: 32
    t_agent_amount: 100
    turning_food_cost: 0.0005
    use_temp: true
    walking_food_cost: 0.002
    walking_in_water_cost: 0.008
